### ISSUE TITLE
Umbraco 10 Country Personalisation

### ISSUE THREAD

**Issue by ANT-GBR** [AndyButland/UmbracoPersonalisationGroupsCore#9]
Hi Andy,

I'm trying to use the country personalisation on an Umbraco 10 site that was upgraded from an Umbraco 8 site. The visitors were correctly being identified as being from the US on the Umbraco 8 site but not after the upgrade. The site is Umbraco 10.4.0 with UmbracoPersonalisationGroups 3.2.3.

Also, whilst investigating this issue I've tried to add configuration to appsettings.json but it isn't being applied.

I've tried:

"personalisationGroups.disabled": true,

and

"personalisationGroups": { "disabled": true }

at various points in the tree but Personalisation Groups are still working.

Thanks 
Tony

**Comment by AndyButland** [comment]
Hi Tony - for configuration of the package with that setting you would need:

```
  "Umbraco": {
    "PersonalisationGroups": {
      "DisablePackage": true
    }
  }
```

I've just tested that and it picks up OK.

I realise this wasn't obvious as I hadn't updated the readme to show the new configuration approach in Umbraco 9+.  I've done that now.

With regard to geolocation, these by default depend on a MaxMind database as you can [read here](Fixed default configuration of geolocation databases.).  As of 3.2.4, which I've just released, these will be looked for in `/umbraco/Data/PersonalisationGroups/`. or you can configure a different path.

Again I've updated the readme file to make this clearer, as I still had some references there from the Umbraco 8 version of this package.

Please let me know how that goes for you.

**Comment by ANT-GBR** [comment]
Hi Andy,

Thanks for your fix on the configuration docs, I've got that working.

I still can't get the geolocation working. I have put the MaxMind country database in /umbraco/Data/PersonalisationGroups/GeoLite2-Country.mmdb but on my dev server it isn't recognising the US VPN location I am trying.

**Comment by AndyButland** [comment]
Hmm... you might need to debug a little to see what IP is being picked up in your setup.  You can see the logic I'm using to get this [here](https://github.com/AndyButland/UmbracoPersonalisationGroupsCore/tree/main/PersonalisationGroups.Core/Providers/Ip), in particular `ClientIpParser` which is responsible for trying to figure out the requesting IP from the headers.

If you copy the relevant parts of that into your web application and see what headers are available and what IP is being picked up, you may be able to find the issue.

**Comment by ANT-GBR** [comment]
When I run your code on the remote server it is returning an empty string and I don't really understand how that code is working.
When I use `_httpContextAccessor.HttpContext.Connection.RemoteIpAddress.ToString()` the correct IP address is displayed.

**Comment by AndyButland** [comment]
Looks like we need a fallback to that if the IP can't be found from the headers.  I've implemented that in 3.2.5, so please see if that resolves the issue for you.

**Comment by ANT-GBR** [comment]
Yes that's fixed it.
Thanks for your help Andy!
